version: '3.3'
services:
  db:
    image: postgres:latest
    volumes:
      - db_value:/var/lib/postgresql/data/
    env_file:
      - ./.env
  web:
    image: siellph/api_yamdb:latest
    build: siellph/api_yamdb:latest
    restart: always
    volumes:
      - static_value:/app/api_yamdb/static/
      - media_value:/app/api_yamdb/media/
    depends_on:
      - db
    env_file:
      - ./.env
  nginx:
    image: nginx:1.21.3-alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - static_value:/var/html/static/
      - media_value:/var/html/media/
    depends_on:
      - web
volumes:
  db_value:
  static_value:
  media_value:
